### ISSUE TITLE
Support for SQLite (updated description) also some file restructuring

### ISSUE THREAD

**Issue by evangelosmeklis** [PeepDB-dev/peepdb#24]
This should be added to release 0.1.4 (after 0.1.3 is released)

**Comment by ArthureVarghese** [comment]
I think it will be better to split logics of each db separately. This could help when adding more features and also when adding additional databases.

**Comment by evangelosmeklis** [comment]
@ArthureVarghese Hey thanks for the suggestion. This is a good idea. Probably creating a file for each database which will then be called by the core.py ex: mysql.py, postgres.py, mariadb.py. I am planning to make a new release tomorrow or monday, then we can restructure. If you want to try feel free, otherwise I will do it

**Comment by ArthureVarghese** [comment]
Yeah sure. I'll try. Thank You

**Comment by ArthureVarghese** [comment]
@evangelosmeklis  Should I do this after next release or start from now?

**Comment by evangelosmeklis** [comment]
@ArthureVarghese Just start now if you want. I will do the release and you can pull the changes and fix any conflicts. I think there will not be many.

**Comment by ArthureVarghese** [comment]
@evangelosmeklis I have a basic version of the changes. Should i submit a PR? I have some more ideas/suggestions to improve them.

**Comment by evangelosmeklis** [comment]
@ArthureVarghese yes please do submit it! Make sure you run the unittests before making the pr and also if you have added new stuff create a unittest for them. For new features discussion please open an issue with label feature 😁

**Comment by evangelosmeklis** [comment]
I will continue this and start by adding SQLite support this week
