### ISSUE TITLE
Support for MongoDB

### ISSUE THREAD

**Issue by evangelosmeklis** [PeepDB-dev/peepdb#33]
Add support for mongodb. Need to think of the design etc. This was asked in Hacker News so it would be a good idea to implement

**Comment by PK470** [comment]
Since mongodb is schema less its hard to present it in table. instead of it could be done as a json object.

**Comment by evangelosmeklis** [comment]
> Since mongodb is schema less its hard to present it in table. instead of it could be done as a json object.
> 
> 

Yes the first commits of the project were to present the answer as json , now by default it appears as a table but you can still represent it as json. So yes for mongo I think json would be the solution here

**Comment by evangelosmeklis** [comment]
I will also close  this issue because it was added by another collaborator
