### ISSUE TITLE
Using class for DB types

### ISSUE THREAD

**Issue by ArthureVarghese** [PeepDB-dev/peepdb#36]
I think a better way would be to write the dbtypes as a classes.
This means creating connection using `__init__()` and `cursor` will be part of the object.
So the `dbtype` and `cursor` need not be passed into functions
and a another function to close the connection after use.
If we use same function names inside all classes, we can implement something like a start function which assigns the correct db object.
Also this means less `if else` checks as we assign it only at the begining.

Also maybe Inherit from a abstract class at top could be an addon so when adding new types it would be easy.
I think this would be a good approach to not to have too many write/modify the code at core.py

```python
class Mysql:
    def __init__(self, host, user, password, database, port, **kwargs):
        """Initialize connection and cursor."""
        self.conn = ...  # Create a connection
        self.cursor = ...  # Create a cursor

    def fetch_tables(self):
        

    def close(self):
        """Close the cursor and connection."""
    

if db_type == "mysql":
    db_object = Mysql('host', 'user', 'password', 'database', port, **kwargs)
elif db_type == "mariadb":
    db_object = Mariadb('host', 'user', 'password', 'database', port, **kwargs)
tables = db_object.fetch_tables()
db_object.close()
```

**Comment by evangelosmeklis** [comment]
makes a lot of sense to do it like this please proceed if you got the time, otherwise I can take it. I will be adding support for SQLite this week

**Comment by ArthureVarghese** [comment]
@Aherontas  I agree with you. That would help to develop a pattern for the DB functions. @evangelosmeklis  I will be quite busy for some weeks so I think it would be better if one of you do it

**Comment by evangelosmeklis** [comment]
@ArthureVarghese Ok I ll start the implementation. Thanks a lot for the suggestions!
