### ISSUE TITLE
Duplicate "No saved connections" message appears despite existing database connections

### ISSUE THREAD

**Issue by daniell-olaitan** [PeepDB-dev/peepdb#42]
**Issue Description**
When listing saved database connections, an incorrect message is displayed at the end of the output. Even though there are active connections, the message "No saved connections" appears after the list of connections. The expected output should only list the existing connections without the extra "No saved connections" message.

**Steps to reproduce the issue**
1. Save multiple database connections (e.g., MySQL and PostgreSQL).
2. Retrieve and display the list of saved connections.

**Expected behavior**
```bash
Saved connections:
- myapp_db (mysql)
- analytics_db (postgres)
```

**Actual behaviour**
```bach
Saved connections:
- myapp_db (mysql)
- analytics_db (postgres)
No saved connections.
```
**My Environment**
- Ubuntu 22.04
- Python 3.12.5
- peepdb v0.1.3

**Comment by evangelosmeklis** [comment]
we can close this issue, it was fixed by the pull request
